### ISSUE TITLE
Can't install with pip

### ISSUE THREAD

**Issue by Lufims** [measuredweighed/BSP2OBJ#2]
I can't install with pip, it says "metadata-generation-failed".

**Comment by Lufims** [comment]
And i found the error, PyPI doesn't have the updated version, and tries to install enum instead of enum34.

**Comment by fgetcat** [comment]
I got the exact same error, did you solve it?

**Comment by Lufims** [comment]
> I got the exact same error, did you solve it?

Download the source code, then use the"setup.py install" command on the bsp2obj folder that have the setup.py
